# Generated by Django 4.1.7 on 2023-03-26 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PiGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('users', models.ManyToManyField(null=True, related_name='user_group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
